<?php
/**
 * dbog .../test/dbog/KeyTest.php
 */

namespace Test\Dbog;

use Test\CoreTestCase;

class KeyTest extends CoreTestCase
{

    public function testAddedPk()
    {
        $config = $this->table->getConfiguration();
        $config->addPrimary();
        $this->assertInstanceOf(\Src\Core\Key\Primary::class, $config->getKeyPrimary());
        $this->assertTrue($config->getKeyPrimary()->isAutoincremental());
        $this->assertEquals($config->getKeyPrimary()->getName(), 'pk_test_table_template');

        // column added automatically
        $this->assertCount(1, $config->getColumns());
        $this->assertArrayHasKey('id_test_table_template', $config->getColumns());
        $this->assertEquals('id_test_table_template', $config->getColumns()['id_test_table_template']->getName());
    }

    public function testAddedUq()
    {
        $config = $this->table->getConfiguration();
        $config->addColumn('new_column');
        $config->addColumn('another_column');
        $config->addKeyUnique(['new_column']);
        $uq = $config->addKeyUnique(['another_column']);

        // two UQs added
        $this->assertCount(2, $config->getKeysUnique());

        // test autogenerated name
        $this->assertEquals('uq_test_table_template_new_column', $config->getKeysUnique()[0]->getName());

        //test custom name
        $uq->setCustomKeyName('uq_custom_name');
        $this->assertEquals('uq_custom_name', $config->getKeysUnique()[1]->getName());
    }

    public function testAddedIx()
    {
        $config = $this->table->getConfiguration();
        $config->addColumn('ix_column');

        $ix = $config->addKeyIndex(['ix_column']);

        $this->assertCount(1, $config->getKeysIndex());

        // test autogenerated name
        $this->assertEquals('ix_test_table_template_ix_column', $config->getKeysIndex()[0]->getName());

        //test prefix length
        $this->assertNull($ix->getPrefixLength('ix_column'));
        $ix->setPrefixLength('ix_column', 12);
        $this->assertEquals(12, $ix->getPrefixLength('ix_column'));
    }
}
